drop procedure admincontrols_Delete
drop procedure admincontrols_List
drop procedure admincontrols_Save
drop procedure modules_Delete
drop procedure modules_Save
drop procedure modules_List
drop procedure discussionproviders_Save
drop procedure discussionproviders_List
drop procedure discussionproviders_Delete
drop procedure admincontrols_Delete
drop procedure admincontrols_Save
drop procedure admincontrols_List
drop procedure modulecontrols_Delete
drop procedure modulecontrols_Save
drop procedure modulecontrols_List
drop procedure templates_Delete
drop procedure templates_Save
drop procedure templates_List
drop procedure routes_Delete
drop procedure routes_Save
drop procedure routes_List
drop procedure permissionflags_Delete
drop procedure permissionflags_Save
drop procedure permissionflags_List
drop procedure rssfeeds_Delete
drop procedure rssfeeds_Save
drop procedure rssfeeds_List
drop procedure authors_Delete
drop procedure authors_Save
drop procedure authors_List
