<?xml version="1.0" encoding="utf-8"?>
<Database Name="mubble" EntityNamespace="Mubble.Data.Raw" Class="DatabaseContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=mubble;Integrated Security=True" SettingsObjectName="Mubble.Data.Properties.Settings" SettingsPropertyName="mubbleConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdminControls" Member="AdminControls">
    <Type Name="AdminControl">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ModuleControlID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ModuleControl_AdminControl" Member="ModuleControl" ThisKey="ModuleControlID" Type="ModuleControl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TextBlocks" Member="TextBlocks">
    <Type Name="TextBlock">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Excerpt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="TextBlock_ContentItem" Member="ContentItems" OtherKey="TextBlockID" Type="ContentItem" />
      <Association Name="TextBlock_Page" Member="Pages" OtherKey="TextBlockID" Type="Page" />
    </Type>
  </Table>
  <Table Name="dbo.Authors" Member="Authors">
    <Type Name="Author">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Displayname" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Bio" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Author_ContentItemAuthor" Member="ContentItemAuthors" OtherKey="AuthorID" Type="ContentItemAuthor" />
    </Type>
  </Table>
  <Table Name="dbo.ContentItemAuthors" Member="ContentItemAuthors">
    <Type Name="ContentItemAuthor">
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="AuthorID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Author_ContentItemAuthor" Member="Author" ThisKey="AuthorID" Type="Author" IsForeignKey="true" />
      <Association Name="ContentItem_ContentItemAuthor" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContentItems" Member="ContentItems">
    <Type Name="ContentItem">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PublishDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentTypeID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TextBlockID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="ContentItem_ContentItemAuthor" Member="ContentItemAuthors" OtherKey="ContentItemID" Type="ContentItemAuthor" />
      <Association Name="ContentItem_ContentItem" Member="ContentItems" OtherKey="ContentItemID" Type="ContentItem" />
      <Association Name="ContentItem_Controller" Member="Controller" OtherKey="ContentItemID" Type="Controller" Cardinality="One" />
      <Association Name="ContentItem_Discussion" Member="Discussions" OtherKey="ContentItemID" Type="Discussion" />
      <Association Name="ContentItem_File" Member="Files" OtherKey="ContentItemID" Type="File" />
      <Association Name="ContentItem_Page" Member="Pages" OtherKey="ContentItemID" Type="Page" />
      <Association Name="ContentItem_ScheduledCommand" Member="ScheduledCommands" OtherKey="ContentItemID" Type="ScheduledCommand" />
      <Association Name="ContentItem_Tag" Member="Tags" OtherKey="ContentItemID" Type="Tag" />
      <Association Name="ContentItem_UrlRedirect" Member="UrlRedirects" OtherKey="ContentItemID" Type="UrlRedirect" />
      <Association Name="ContentItem_ContentItem" Member="ContentItem1" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
      <Association Name="TextBlock_ContentItem" Member="TextBlock" ThisKey="TextBlockID" Type="TextBlock" IsForeignKey="true" />
      <Association Name="ContentType_ContentItem" Member="ContentType" ThisKey="ContentTypeID" Type="ContentType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContentTypes" Member="ContentTypes">
    <Type Name="ContentType">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SystemType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ActiveObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ContentType_ContentItem" Member="ContentItems" OtherKey="ContentTypeID" Type="ContentItem" />
    </Type>
  </Table>
  <Table Name="dbo.Controllers" Member="Controllers">
    <Type Name="Controller">
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TemplateID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TemplateControl" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ModuleControlID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ModuleControlView" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RouteID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="IsContent" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="IsContentContainer" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Settings" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Controller_Permission" Member="Permissions" OtherKey="ControllerID" Type="Permission" />
      <Association Name="Controller_RssFeed" Member="RssFeeds" OtherKey="ControllerID" Type="RssFeed" />
      <Association Name="ContentItem_Controller" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
      <Association Name="ModuleControl_Controller" Member="ModuleControl" ThisKey="ModuleControlID" Type="ModuleControl" IsForeignKey="true" />
      <Association Name="Template_Controller" Member="Template" ThisKey="TemplateID" Type="Template" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DiscussionProviders" Member="DiscussionProviders">
    <Type Name="DiscussionProvider">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ActiveObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Settings" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DiscussionProvider_Discussion" Member="Discussions" OtherKey="DiscussionProviderID" Type="Discussion" />
    </Type>
  </Table>
  <Table Name="dbo.Discussions" Member="Discussions">
    <Type Name="Discussion">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DiscussionProviderID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DiscussionLink" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastStatusMessage" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CommentCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ContentItem_Discussion" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
      <Association Name="DiscussionProvider_Discussion" Member="DiscussionProvider" ThisKey="DiscussionProviderID" Type="DiscussionProvider" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Files" Member="Files">
    <Type Name="File">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PhysicalPath" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MediaType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MediaSubType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ContentItem_File" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ModuleControls" Member="ModuleControls">
    <Type Name="ModuleControl">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ModuleID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ControllerActiveObjectType" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsContent" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsContentContainer" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="ModuleControl_AdminControl" Member="AdminControls" OtherKey="ModuleControlID" Type="AdminControl" />
      <Association Name="ModuleControl_Controller" Member="Controllers" OtherKey="ModuleControlID" Type="Controller" />
      <Association Name="ModuleControl_Route" Member="Routes" OtherKey="ModuleControlID" Type="Route" />
      <Association Name="Module_ModuleControl" Member="Module" ThisKey="ModuleID" Type="Module" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Modules" Member="Modules">
    <Type Name="Module">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Module_ModuleControl" Member="ModuleControls" OtherKey="ModuleID" Type="ModuleControl" />
      <Association Name="Module_PermissionFlag" Member="PermissionFlags" OtherKey="ModuleID" Type="PermissionFlag" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PageNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TextBlockID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="ContentItem_Page" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
      <Association Name="TextBlock_Page" Member="TextBlock" ThisKey="TextBlockID" Type="TextBlock" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PermissionFlags" Member="PermissionFlags">
    <Type Name="PermissionFlag">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Flag" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ModuleID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Module_PermissionFlag" Member="Module" ThisKey="ModuleID" Type="Module" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Permissions" Member="Permissions">
    <Type Name="Permission">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ControllerID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[Group]" Member="Group" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Flag" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Controller_Permission" Member="Controller" ThisKey="ControllerID" Type="Controller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Routes" Member="Routes">
    <Type Name="Route">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Pattern" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ModuleControlID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="[Order]" Member="Order" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FormatString" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ModuleControl_Route" Member="ModuleControl" ThisKey="ModuleControlID" Type="ModuleControl" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RssFeeds" Member="RssFeeds">
    <Type Name="RssFeed">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ManagingEditor" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ItemFormat" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slug" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RedirectUrl" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RedirectExceptions" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ControllerID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Association Name="Controller_RssFeed" Member="Controller" ThisKey="ControllerID" Type="Controller" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ScheduledCommands" Member="ScheduledCommands">
    <Type Name="ScheduledCommand">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="RunAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Command" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ContentItem_ScheduledCommand" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tags" Member="Tags">
    <Type Name="Tag">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="StringValue" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StringValueNormalized" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NumericValue" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="NormalizeStringValue" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="ContentItem_Tag" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Templates" Member="Templates">
    <Type Name="Template">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="UpdatedAt" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Template_Controller" Member="Controllers" OtherKey="TemplateID" Type="Controller" />
    </Type>
  </Table>
  <Table Name="dbo.UrlRedirects" Member="UrlRedirects">
    <Type Name="UrlRedirect">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="PathExtra" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ContentItemID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Handler" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="ContentItem_UrlRedirect" Member="ContentItem" ThisKey="ContentItemID" Type="ContentItem" IsForeignKey="true" />
    </Type>
  </Table>
</Database>